-- 配置参数（完全对应JSON，可直接修改）
local Config = {
    -- 开关类
    NotifyHideTime = true,
    NotPadlockCode = true,
    Godmode = true,
    AntiA90 = true,
    WalkSpeed = true,
    AntiJumpscares = true,
    FOVToggle = false,
    ["Visual-Notifier-Entities"] = true,
    NotifyOxygen = true,
    AntiDread = true,
    AntiJam = true,
    AntiShade = true,
    ["Chat-Notifier"] = true,
    AntiEyes = true,
    AutoBreakerSolver = true,
    Fly = true,
    ["Visual-esp-gold"] = true,
    ShowCustomCursor = true,
    ["esp-rainbow"] = false,
    ["Always Win Heartbeat"] = true,
    ["Visual-esp-door"] = true,
    ["Visual-esp-player"] = true,
    ["esp-tracers"] = true,
    ["Auto-interact"] = true,
    ["AntiSeekObstructions"] = true,
    ["AntiCutscenes"] = true,
    ["Main-Insta-Interact"] = true,
    NoCamShake = true,
    AntiJeffServer = false,
    ["Troll-Stunned-animation"] = false,
    ["Visual-No-Wardobre-Vignette"] = true,
    LibraryBruteForce = true,
    Fullbright = true,
    SpeedBypass = true,
    AntiGiggle = true,
    WaterMarkToggle = false,
    ["Visual-esp-objective"] = true,
    ["Visual-Notifier-Events"] = true,
    AutoLibraryCode = true,
    ["esp-arrows"] = false,
    NoPuzzleDoor = true,
    ["Auto Execute On Teleport"] = false,
    ["No Accelerarion"] = true,
    PromptClip = true,
    ["Visual-esp-hidingspot"] = true,
    ["AntiFigureHearing"] = true,
    ["Visual-esp-entity"] = true,
    GlitchFragmentToggle = false,
    ["Troll-Thoughts"] = false,
    InfiniteItems = true,
    AnticheatManipulation = false,
    ["Anti-Dupe"] = true,
    NoFog = true,
    AntiLag = true,
    EnableJump = false,
    ["Enable Sliding"] = false,
    ["Visual-no-ambience"] = true,
    ThirdPerson = false,
    AntiJeffClient = true,
    KeybindMenuOpen = false,
    NoCrouchBarriers = true,
    ["Visual-esp-item"] = true,
    DoorReach = true,
    SpamOtherTools = false,
    UpsideDown = false,
    AntiScreech = true,
    ["Anti-Snare"] = true,

    -- 颜色类（Hex转Color3）
    ["EntityEsp-color"] = Color3.fromHex("ff0000"),
    ["GoldEsp-color"] = Color3.fromHex("ffff00"),
    ["ItemEsp-color"] = Color3.fromHex("ff00ff"),
    ["ObjectiveEsp-color"] = Color3.fromHex("00ff00"),
    ["PlayerEsp-color"] = Color3.fromHex("ffffff"),
    ["DoorEsp-color"] = Color3.fromHex("00ffff"),
    ["HidingSpotEsp-color"] = Color3.fromHex("008000"),

    -- 数值类
    FlySpeed = 75,
    JumpBoost = 0,
    MaxActivationDistance = 7,
    WalkSpeedVelocity = 75,
    LibraryDistance = 120,
    SpeedBypassDelay = 0.222,
    Brightness = 1.3,
    FOVSlider = 70,
    ["esp-outline"] = 0,
    ["esp-textsize"] = 26,

    -- 下拉菜单类
    LanguageSelector = "Select language",
    notifyStyle = "Doors",
    EntitySelection = {All = true},
    LocalTrace = "Bottom",
    AutoBreakerSolverMethod = "Legit",
    LibraryDropdown = "Selecione",
    DPIDropdown = "100%",
    NotificationSide = "Right",
    ["Auto-interact-drop"] = {["Jeff Items"] = true, ["GlitchCub"] = true, ["Mandrake"] = true},

    -- 按键绑定类
    ["KeyF-fly"] = {key = "F", mode = "Toggle"},
    GodmodeKeybind = {key = "G", mode = "Toggle"},
    AmtiCheatManipulationKeybind = {key = "Q", mode = "Toggle"},
    ["KeyC-ThirdPerson"] = {key = "C", mode = "Toggle"},
    ["KeyP-autointeract"] = {key = "P", mode = "Toggle"},
    EntityMessage = "%s foi gerado!"
}

return Config
